include("lib_for_robot.jl")
function task13(r)
    putmarker!(r)
    side=(Nord,Ost)
    x,y = move_diog(r,side)
    rtn_diog(r,side,x,y)
    side=(West,Nord)
    x,y = move_diog(r,side)
    rtn_diog(r,side,x,y)
    side=(Sud,West)
    x,y = move_diog(r,side)
    rtn_diog(r,side,x,y)
    side=(Sud,Ost)
    x,y = move_diog(r,side)
    rtn_diog(r,side,x,y)
end